### ISSUE TITLE
./../resources/alanine_dipeptide.pdb is not found

### ISSUE THREAD

**Issue by HanatoK** [weiHelloWorld/accelerated_sampling_with_autoencoder#64]
I encountered this error when I ran `python3 ./main_work.py`:
```
Traceback (most recent call last):
  File "./config.py", line 61, in <module>
    get_index_list_with_selection_statement('../resources/alanine_dipeptide.pdb', 'name C or name CH3 or name CA or name N'),
  File "./config.py", line 42, in get_index_list_with_selection_statement
    return (Universe(pdb_file_1).select_atoms(atom_selection_statement).indices + 1).tolist()
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/core/universe.py", line 300, in __init__
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/core/universe.py", line 292, in __init__
    self._topology = p.parse(**kwargs)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/topology/PDBParser.py", line 183, in parse
    top = self._parseatoms()
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/topology/PDBParser.py", line 216, in _parseatoms
    with util.openany(self.filename ) as f:
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 309, in openany
    stream = anyopen(datasource, mode=mode, reset=reset)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 396, in anyopen
    stream = _get_stream(datasource, openfunc, mode=mode)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 438, in _get_stream
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 432, in _get_stream
    stream = openfunction(filename, mode=mode)
  File "/usr/lib64/python3.7/bz2.py", line 318, in open
    binary_file = BZ2File(filename, bz_mode, compresslevel=compresslevel)
  File "/usr/lib64/python3.7/bz2.py", line 92, in __init__
    self._fp = _builtin_open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: './../resources/alanine_dipeptide.pdb'
```
Where can I find the missing pdb file?

**Comment by weiHelloWorld** [comment]
Hi, Thanks for your interest!  You may find the file here: https://drive.google.com/file/d/1stCYe3ZGg3GnOrbVqCX_pu2uQ6Frxx6x/view?usp=sharing.  Let me know if you have any questions.

**Comment by HanatoK** [comment]
> Hi, Thanks for your interest! You may find the file here: https://drive.google.com/file/d/1stCYe3ZGg3GnOrbVqCX_pu2uQ6Frxx6x/view?usp=sharing. Let me know if you have any questions.

Thanks for your reply! I downloaded the file but it is alanine_dipeptide.ipynb and not alanine_dipeptide.pdb. I opened alanine_dipeptide.ipynb and didn't find where to download alanine_dipeptide.pdb.

**Comment by weiHelloWorld** [comment]
Sorry, it should be this one: https://drive.google.com/file/d/1SjFvrF7M4espMSS5bW1n-bwmY8pRkKZP/view?usp=sharing.  Let me know if you have any issues.

**Comment by HanatoK** [comment]
@weiHelloWorld Now the script complains about missing `1l2y.pdb`:
```
Traceback (most recent call last):
  File "./main_work.py", line 1, in <module>
    from ANN_simulation import *
  File "/home/yjcoshc/HDD/software/accelerated_sampling_with_autoencoder/MD_simulation_on_alanine_dipeptide/current_work/src/ANN_simulation.py", line 1, in <module>
    from config import * # configuration file
  File "/home/yjcoshc/HDD/software/accelerated_sampling_with_autoencoder/MD_simulation_on_alanine_dipeptide/current_work/src/config.py", line 63, in <module>
    get_index_list_with_selection_statement('../resources/1l2y.pdb', 'backbone and not name O'),
  File "/home/yjcoshc/HDD/software/accelerated_sampling_with_autoencoder/MD_simulation_on_alanine_dipeptide/current_work/src/config.py", line 42, in get_index_list_with_selection_statement
    return (Universe(pdb_file_1).select_atoms(atom_selection_statement).indices + 1).tolist()
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/core/universe.py", line 300, in __init__
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/core/universe.py", line 292, in __init__
    self._topology = p.parse(**kwargs)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/topology/PDBParser.py", line 183, in parse
    top = self._parseatoms()
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/topology/PDBParser.py", line 216, in _parseatoms
    with util.openany(self.filename ) as f:
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 309, in openany
    stream = anyopen(datasource, mode=mode, reset=reset)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 396, in anyopen
    stream = _get_stream(datasource, openfunc, mode=mode)
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 438, in _get_stream
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/python3.7/site-packages/MDAnalysis/lib/util.py", line 432, in _get_stream
    stream = openfunction(filename, mode=mode)
  File "/usr/lib64/python3.7/bz2.py", line 318, in open
    binary_file = BZ2File(filename, bz_mode, compresslevel=compresslevel)
  File "/usr/lib64/python3.7/bz2.py", line 92, in __init__
    self._fp = _builtin_open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yjcoshc/HDD/software/accelerated_sampling_with_autoencoder/MD_simulation_on_alanine_dipeptide/current_work/src/../resources/1l2y.pdb'
```
I have a look at the scripts and they require a lot of files in the `MD_simulation_on_alanine_dipeptide/current_work/resources` directory. However, it's empty in your repository. Could you please upload all the necessary files in `MD_simulation_on_alanine_dipeptide/current_work/resources`?
Thanks!

**Comment by rberg2** [comment]
I was trying to run the tests and hit this same error. I was able to find some of these files.

https://raw.githubusercontent.com/choderalab/openmm-tutorials/master/resources/alanine-dipeptide-implicit.pdb
https://files.rcsb.org/download/1L2Y.pdb
https://files.rcsb.org/download/2SRC.pdb
Betahairpin.pdb is in here https://www.plumed.org/doc-v2.7/user-doc/html/tutorial-resources/lugano-5.tar.gz
C24.pdb https://files.rcsb.org/download/6OV6.pdb

**Comment by weiHelloWorld** [comment]
@rberg2 @HanatoK 

Sorry for the late reply!  1l2y.pdb and 2src.pdb are here: 

https://drive.google.com/drive/folders/1G0jR5fj3Jc80_IjgXqj6sFwH04XovNAq?usp=sharing.
